# Generated by Django 3.2.8 on 2022-06-26 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridareawithcharacter',
            name='character',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gridareawithcharacter',
            name='color',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
