# Generated by Django 3.2.8 on 2022-04-21 18:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.IntegerField()),
                ('race', models.CharField(blank=True, max_length=100, null=True)),
                ('combat_class', models.CharField(blank=True, max_length=100, null=True)),
                ('background', models.CharField(blank=True, max_length=100, null=True)),
                ('alignment', models.CharField(blank=True, max_length=100, null=True)),
                ('exp', models.IntegerField(default=0)),
                ('main_strength', models.IntegerField(default=0)),
                ('main_dexterity', models.IntegerField(default=0)),
                ('main_constitution', models.IntegerField(default=0)),
                ('main_intelligence', models.IntegerField(default=0)),
                ('main_wisdom', models.IntegerField(default=0)),
                ('main_charisma', models.IntegerField(default=0)),
                ('inspiration', models.IntegerField(default=0)),
                ('proficiencybonus', models.IntegerField(default=0)),
                ('saving_strength', models.IntegerField(default=0)),
                ('saving_dexterity', models.IntegerField(default=0)),
                ('saving_constitution', models.IntegerField(default=0)),
                ('saving_intelligence', models.IntegerField(default=0)),
                ('saving_wisdom', models.IntegerField(default=0)),
                ('saving_charisma', models.IntegerField(default=0)),
                ('armorclass', models.IntegerField(default=0)),
                ('initiative', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('current_hp', models.IntegerField(default=0)),
                ('temporary_hp', models.IntegerField(default=0)),
                ('hit_dice', models.IntegerField(default=0)),
                ('deathsaves_success', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('deathsaves_failure', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(3)])),
                ('acrobatics', models.IntegerField(default=0)),
                ('animalhandling', models.IntegerField(default=0)),
                ('arcana', models.IntegerField(default=0)),
                ('athletics', models.IntegerField(default=0)),
                ('deception', models.IntegerField(default=0)),
                ('history', models.IntegerField(default=0)),
                ('insight', models.IntegerField(default=0)),
                ('intimidation', models.IntegerField(default=0)),
                ('investigation', models.IntegerField(default=0)),
                ('medicine', models.IntegerField(default=0)),
                ('nature', models.IntegerField(default=0)),
                ('perception', models.IntegerField(default=0)),
                ('performance', models.IntegerField(default=0)),
                ('persuation', models.IntegerField(default=0)),
                ('religion', models.IntegerField(default=0)),
                ('sleightofhand', models.IntegerField(default=0)),
                ('stealth', models.IntegerField(default=0)),
                ('survival', models.IntegerField(default=0)),
                ('passive_wisdom', models.IntegerField(default=0)),
                ('equipment', models.TextField(default='', max_length=300)),
                ('proficiencies', models.TextField(default='', max_length=300)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
