# Generated by Django 3.2.4 on 2021-07-30 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charsheets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='combat_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='charsheets.combatclass'),
        ),
    ]
