# Generated by Django 4.0.1 on 2022-01-17 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charsheets', '0002_alignment_background_character_acrobatics_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='exp',
            field=models.IntegerField(default=0),
        ),
    ]
