# Generated by Django 3.2.8 on 2021-10-31 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chat',
            old_name='User',
            new_name='user',
        ),
    ]
