# Generated by Django 3.2.8 on 2021-12-20 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('charsheets', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='characterbelongstoroom',
            unique_together={('character', 'room')},
        ),
    ]
