# Generated by Django 3.2.8 on 2022-06-28 16:11

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_alter_chatroom_gamemaster'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chat',
            new_name='ChatMessage',
        ),
    ]
