# Generated by Django 3.2.8 on 2021-10-31 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_chat_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat',
            name='timestamp',
            field=models.CharField(max_length=7),
        ),
    ]
