# Generated by Django 3.2.8 on 2022-01-18 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('charsheets', '0003_character_exp'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserToRoomRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(null=True)),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='charsheets.character')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatroom')),
            ],
            options={
                'unique_together': {('character', 'room')},
            },
        ),
    ]
